<?php

/**
 * @file
 * Contains user_register_extend.module.
 */
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\user\Entity\User;

/**
 * Implements hook_help().
 */
function user_register_extend_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the user_register_extend module.
    case 'help.page.user_register_extend':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Extend functionalities for user register') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function user_register_extend_theme() {
  return [
    'coupon_block' => [
      'variables' => [
        'data' => ['offer' => NULL],
      ]
    ]
  ];
}